services:
  bot-asistencia:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./credentials.json:/app/credentials.json
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 500M
    environment:
      - PYTHONUNBUFFERED=1
